Feature/iban list screen
razmaa/Collaboration-IBanSaverApp pull request #18
Opened 2024-01-13 23:41 UTC by razmaa

Merge Request for 'feature/iban_list_screen' Branch into Main Branch.

The 'feature/iban_list_screen' branch includes the following files and functionalities:

IBanListVIew:

Presents list of persons
Navigates to AddPersonView

IBanDetailsView:

Presents info about person's IBans and banks
Navigates to AddIbanView

IBanDetailsViewModel:

Stores info to display on IBanDetailsView

2024-01-13 23:43 UTC, razmaa commented
> Merge Request for 'feature/iban_list_screen' Branch into Main Branch.
> 
> The 'feature/iban_list_screen' branch includes the following files and functionalities:
> 
> IBanListVIew:
> 
> Presents list of persons Navigates to AddPersonView
> 
> IBanDetailsView:
> 
> Presents info about person's IBans and banks Navigates to AddIbanView
> 
> IBanDetailsViewModel:
> 
> Stores info to display on IBanDetailsView

This text was inspired by Eka

2024-01-14 10:01 UTC, ekakele requested changes

2024-01-14 10:01 UTC, ekakele commented on IBanSaverApp-Collaboration/Screens/IBanList/IBanDetailsView/IBanDetailsView.swift
> +                            IBanRow(
ცალკე რომ გაგეტანა უკეთესი იქნებოდა.

2024-01-14 10:01 UTC, ekakele commented on IBanSaverApp-Collaboration/Screens/IBanList/IBanDetailsView/IBanDetailsViewModel.swift
> +    @Published var IBans: [Bank: [IBAN]]
ამ გევრდზე მარკები გაკლია.

2024-01-14 10:01 UTC, ekakele commented on IBanSaverApp-Collaboration/Screens/IBanList/IBanDetailsView/IBanRow.swift
> +                Image(systemName: "doc.on.doc")
ამ აიქონებს ფერები ექსთენშენიდან მიეცი, blue.

2024-01-14 10:01 UTC, ekakele commented on IBanSaverApp-Collaboration/Screens/IBanList/IBanDetailsView/IBanRow.swift
> +    let iban: String
მარკები.

2024-01-14 10:01 UTC, ekakele commented on IBanSaverApp-Collaboration/Screens/IBanList/IBanListView.swift
> +                            let detailsView = IBanDetailsViewRepresentable(person: person)
ეს ცალკე ფუქნციაში რომ გაიტანო დ აქ გამოიძახო, ჯობია.

2024-01-14 10:13 UTC, likanozadze commented on IBanSaverApp-Collaboration/Screens/IBanList/IBanListView.swift
> +                            let detailsView = IBanDetailsViewRepresentable(person: person)
ვეთანხმები ეკას

2024-01-14 10:13 UTC, likanozadze commented on IBanSaverApp-Collaboration/Screens/IBanList/IBanListView.swift
> +
ზედმეტი გამოტოვებები გაქვს ბევრგან

2024-01-14 10:14 UTC, likanozadze requested changes
ზედმეტი გამოტოვებები, მარკები რომ გაასწორო

2024-01-14 11:20 UTC, ekakele approved these changes

2024-01-14 11:24 UTC, likanozadze approved these changes

2024-01-14 11:28 UTC, merged